-- =============================================================================
-- Doom Scroll Gov Contracts — Database Schema
-- Run this in Supabase: SQL Editor → New Query → paste → Run
-- =============================================================================


-- =============================================================================
-- COMPANIES
-- One row per company account. This is the core tenant unit.
-- =============================================================================
create table companies (
  id                      uuid primary key default gen_random_uuid(),
  name                    text not null,
  website                 text,

  -- Contract size targeting
  contract_min            numeric,                        -- minimum $ they pursue
  contract_max            numeric,                        -- maximum $ they pursue

  -- Strategic posture
  prime_sub_preference    text check (prime_sub_preference in ('prime', 'sub', 'both')),
  clearance_level         text check (clearance_level in ('none', 'secret', 'ts', 'tssci')),

  -- Set-aside eligibilities (array — a company can have multiple)
  set_aside_eligibility   text[] default '{}',           -- e.g. ['8a', 'sdvosb', 'small_business']

  -- Geographic focus
  geographic_focus        text[] default '{"CONUS"}',    -- e.g. ['CONUS', 'VA', 'DC']

  -- Raw capabilities statement text (used for AI keyword extraction)
  capabilities_statement  text,

  -- Onboarding state
  onboarding_complete     boolean default false,
  onboarding_step         integer default 1,             -- which step they left off on (1–4)

  created_at              timestamptz default now(),
  updated_at              timestamptz default now()
);


-- =============================================================================
-- USERS
-- Individual users within a company. id mirrors auth.users.id from Supabase Auth.
-- =============================================================================
create table users (
  id          uuid primary key references auth.users(id) on delete cascade,
  company_id  uuid references companies(id) on delete cascade,
  email       text not null,
  full_name   text,
  role        text default 'member' check (role in ('admin', 'member')),
  created_at  timestamptz default now()
);


-- =============================================================================
-- COMPANY NAICS CODES
-- One-to-many: a company can target multiple NAICS codes.
-- =============================================================================
create table company_naics (
  id          uuid primary key default gen_random_uuid(),
  company_id  uuid not null references companies(id) on delete cascade,
  naics_code  text not null,
  description text,
  is_primary  boolean default false,
  created_at  timestamptz default now(),
  unique (company_id, naics_code)
);


-- =============================================================================
-- COMPANY KEYWORDS
-- Capability keywords for matching. Supports positive and exclusion keywords.
-- =============================================================================
create table company_keywords (
  id           uuid primary key default gen_random_uuid(),
  company_id   uuid not null references companies(id) on delete cascade,
  keyword      text not null,
  weight       numeric default 1.0,   -- higher = more important for scoring
  is_exclusion boolean default false, -- true = negative keyword (downrank matches)
  created_at   timestamptz default now(),
  unique (company_id, keyword)
);


-- =============================================================================
-- COMPANY AGENCIES
-- Agencies a company has history with, wants to target, or wants to exclude.
-- =============================================================================
create table company_agencies (
  id                uuid primary key default gen_random_uuid(),
  company_id        uuid not null references companies(id) on delete cascade,
  agency_name       text not null,
  relationship_type text check (relationship_type in ('past_performance', 'target', 'exclude')),
  created_at        timestamptz default now(),
  unique (company_id, agency_name)
);


-- =============================================================================
-- OPPORTUNITIES
-- Bulk-ingested from SAM.gov (and SBIR, Grants.gov). 50k+ rows expected.
-- The ai_summary field is the one-line card text generated by Claude Haiku.
-- =============================================================================
create table opportunities (
  id                           uuid primary key default gen_random_uuid(),

  -- SAM.gov identifiers
  notice_id                    text unique not null,
  solicitation_number          text,

  -- Core fields
  title                        text not null,
  description                  text,
  ai_summary                   text,                   -- Claude-generated one-liner for the card

  -- Agency
  agency                       text,
  sub_agency                   text,
  office                       text,

  -- Classification
  naics_code                   text,
  psc_code                     text,
  set_aside_type               text,                   -- e.g. 'SBA', 'SDVOSBC', '8AN', 'WOSB'
  contract_type                text,                   -- e.g. 'FFP', 'T&M', 'IDIQ'
  notice_type                  text,                   -- 'solicitation', 'presolicitation', 'sources_sought', 'award'

  -- Value
  value_min                    numeric,
  value_max                    numeric,

  -- Place of performance
  pop_city                     text,
  pop_state                    text,
  pop_country                  text default 'USA',

  -- Dates
  posted_date                  timestamptz,
  response_deadline            timestamptz,
  modified_date                timestamptz,

  -- Status lifecycle
  status                       text default 'active' check (status in ('active', 'expired', 'awarded', 'cancelled')),

  -- Source
  source                       text default 'sam_gov' check (source in ('sam_gov', 'sbir', 'grants_gov')),

  -- Attachments stored as JSON array: [{filename, url, size_bytes}]
  attachments                  jsonb default '[]',

  -- Full raw API response — lets us re-parse without re-fetching
  raw_data                     jsonb,

  created_at                   timestamptz default now(),
  updated_at                   timestamptz default now()
);


-- =============================================================================
-- SWIPES
-- Every right/left swipe. This is the core behavioral training data.
-- dwell_ms = how long the user looked at the card before swiping.
-- expanded  = did they tap to read more before deciding?
-- =============================================================================
create table swipes (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references users(id) on delete cascade,
  company_id      uuid not null references companies(id) on delete cascade,
  opportunity_id  uuid not null references opportunities(id) on delete cascade,
  direction       text not null check (direction in ('right', 'left')),
  dwell_ms        integer,            -- milliseconds spent on card before swiping
  expanded        boolean default false,  -- did they open the detail view?
  created_at      timestamptz default now(),

  unique (user_id, opportunity_id)    -- one swipe per user per opportunity
);


-- =============================================================================
-- PIPELINE
-- Opportunities a user has right-swiped and is actively tracking.
-- stage moves left-to-right as the pursuit progresses.
-- =============================================================================
create table pipeline (
  id              uuid primary key default gen_random_uuid(),
  company_id      uuid not null references companies(id) on delete cascade,
  opportunity_id  uuid not null references opportunities(id) on delete cascade,
  created_by      uuid not null references users(id),
  assigned_to     uuid references users(id),
  stage           text default 'watching' check (
                    stage in ('watching', 'evaluating', 'pursuing', 'submitted', 'won', 'lost')
                  ),
  notes           text,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now(),

  unique (company_id, opportunity_id)   -- one pipeline entry per company per opportunity
);


-- =============================================================================
-- SCORER EVALS
-- One row per evaluation run. Used to track whether feed quality is improving.
-- Written by evaluate_scorer() in v2.py, read by the /api/v2/eval endpoint.
-- =============================================================================
create table scorer_evals (
  id                      uuid primary key default gen_random_uuid(),
  company_id              uuid references companies(id) on delete cascade,
  evaluated_at            timestamptz default now(),

  -- Snapshot counts at time of eval
  total_swipes            integer,
  training_swipes         integer,
  holdout_swipes          integer,
  holdout_rights          integer,

  -- Core metric: higher is better; 1.0 = no better than random; target ≥ 1.3
  lift_at_30              numeric,

  -- Discovery metrics
  out_of_naics_like_rate  numeric,   -- fraction of likes outside declared NAICS
  exploration_breadth     integer,   -- unique NAICS codes in liked holdout set

  -- Scorer version tag — bump when algorithm changes so history is comparable
  scorer_version          text,

  notes                   text       -- optional human annotation
);

-- Evals are scoped to the company that owns the data
alter table scorer_evals enable row level security;
create policy "scorer_evals: own company"
  on scorer_evals for all using (company_id = my_company_id());


-- =============================================================================
-- INDEXES
-- Tuned for the queries the app actually runs.
-- =============================================================================

-- Feed queries filter by status and sort by deadline/posted date constantly
create index idx_opportunities_status          on opportunities(status);
create index idx_opportunities_naics           on opportunities(naics_code);
create index idx_opportunities_set_aside       on opportunities(set_aside_type);
create index idx_opportunities_deadline        on opportunities(response_deadline);
create index idx_opportunities_posted          on opportunities(posted_date desc);
create index idx_opportunities_agency          on opportunities(agency);
create index idx_opportunities_modified        on opportunities(modified_date desc);
create index idx_opportunities_notice_type     on opportunities(notice_type);
create index idx_opportunities_value           on opportunities(value_min, value_max);

-- Full-text search on title + description
create index idx_opportunities_fts on opportunities
  using gin(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, '')));

-- Swipe lookups — "what has this user already seen?"
create index idx_swipes_user        on swipes(user_id);
create index idx_swipes_company     on swipes(company_id);
create index idx_swipes_direction   on swipes(user_id, direction);  -- for algorithm: right-swipes only

-- Pipeline board queries
create index idx_pipeline_company   on pipeline(company_id);
create index idx_pipeline_stage     on pipeline(company_id, stage);

-- Company profile lookups
create index idx_company_naics_co   on company_naics(company_id);
create index idx_company_keywords_co on company_keywords(company_id);


-- =============================================================================
-- ROW LEVEL SECURITY (RLS)
-- Each company can only see its own data. Opportunities are public (read-only).
-- The Flask backend uses the service_role key which bypasses RLS entirely.
-- =============================================================================

alter table companies       enable row level security;
alter table users           enable row level security;
alter table company_naics   enable row level security;
alter table company_keywords enable row level security;
alter table company_agencies enable row level security;
alter table swipes          enable row level security;
alter table pipeline        enable row level security;
alter table opportunities   enable row level security;


-- Helper function: get the company_id for the currently logged-in user
create or replace function my_company_id()
returns uuid language sql stable as $$
  select company_id from users where id = auth.uid()
$$;


-- COMPANIES: users can read and update their own company only
create policy "users read own company"
  on companies for select using (id = my_company_id());

create policy "users update own company"
  on companies for update using (id = my_company_id());


-- USERS: users can read other users in their company
create policy "users read own company members"
  on users for select using (company_id = my_company_id());

create policy "users update own profile"
  on users for update using (id = auth.uid());


-- COMPANY_NAICS / KEYWORDS / AGENCIES: scoped to own company
create policy "company naics: own company"
  on company_naics for all using (company_id = my_company_id());

create policy "company keywords: own company"
  on company_keywords for all using (company_id = my_company_id());

create policy "company agencies: own company"
  on company_agencies for all using (company_id = my_company_id());


-- OPPORTUNITIES: all authenticated users can read (it's public government data)
create policy "opportunities: authenticated read"
  on opportunities for select using (auth.role() = 'authenticated');


-- SWIPES: users see and write only their own swipes
create policy "swipes: own user"
  on swipes for all using (user_id = auth.uid());


-- PIPELINE: all members of a company share the pipeline
create policy "pipeline: own company"
  on pipeline for all using (company_id = my_company_id());


-- =============================================================================
-- AUTO-UPDATE updated_at ON ROW CHANGES
-- =============================================================================
create or replace function update_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_companies_updated_at
  before update on companies
  for each row execute function update_updated_at();

create trigger trg_opportunities_updated_at
  before update on opportunities
  for each row execute function update_updated_at();

create trigger trg_pipeline_updated_at
  before update on pipeline
  for each row execute function update_updated_at();
